name = "DesignAutomation"
uuid = "bf082554-cd64-448e-a8ad-8a3ddb3da358"
authors = ["Cameron Irmas <cirmas@protonmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
